WIP Feat/game 14
24-team-09/Arcade-2D-game pull request #14
Opened 2023-04-01 14:44 UTC by Lobanovk

### Какую задачу решаем
https://24-team-09.atlassian.net/browse/GAME-14?atlOrigin=eyJpIjoiYmY2N2QwNmE5YTM3NGI2MzgxN2U2ZTk5NDc1ZjliMDgiLCJwIjoiaiJ9

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-02 04:58 UTC, alheym approved these changes

2023-04-02 05:00 UTC, alheym commented
можно добавить в описание ссылки на sub tasks для этой задачи, чтобы было проще отслеживать процесс работы

2023-04-02 09:12 UTC, Lobanovk commented
> 

добавил

2023-04-02 10:30 UTC, leopard-work approved these changes

2023-04-02 16:05 UTC, ErikKhasanov approved these changes

2023-04-03 09:41 UTC, shoom1337-yt requested changes

2023-04-03 09:41 UTC, shoom1337-yt commented on packages/client/src/App.test.tsx
> +// TODO skip тест, пока он нам не нужен и мешается
ℹ️ Можно ещё завести задачу на доску и сюда поставить ссылку на неё. Можно планировать доработку техдолга не заходя в код.

2023-04-03 09:41 UTC, shoom1337-yt commented on packages/client/src/components/organisms/game/game.component.tsx
> +            onCloseInformation={() => setIsShowInformation(false)}
❓ Хэндлеры нужно вынести из разметки. Так будет проще читать сам компонент и, при необходимости, расширять сами хэндлеры, не внося изменений в разметку.

2023-04-03 09:41 UTC, shoom1337-yt commented on packages/client/src/components/organisms/game/information-view/information-view.types.ts
> +  tooltip: string
ℹ️ Предлагаю вынести на командное обсуждение вопрос о точках с запятой. Где-то они есть, где-то нет. А тут — оба варианта на соседних строчках 🙂

2023-04-03 09:59 UTC, Lobanovk commented on packages/client/src/components/organisms/game/game.component.tsx
> +            onCloseInformation={() => setIsShowInformation(false)}
@shoom1337-yt Поправил

2023-04-03 10:17 UTC, shoom1337-yt approved these changes

2023-04-03 10:18 UTC, merged