Feat/game 42: добавлен redux
24-team-09/Arcade-2D-game pull request #22
Opened 2023-04-10 13:52 UTC by oalbukova

### Какую задачу решаем
задача https://24-team-09.atlassian.net/browse/GAME-42

- добавлен redux
- api авторизации, регистрации, изменения данных, выхода, все формы подключены

### Скриншоты
![image](https://user-images.githubusercontent.com/59943599/230913057-c9976d8f-4b0f-4a38-a981-d28461d7371a.png)

2023-04-10 14:36 UTC, Lobanovk approved these changes

2023-04-10 14:36 UTC, Lobanovk commented on packages/client/src/store/user/userSlice.ts
> +
лишний пропуск

2023-04-10 14:36 UTC, Lobanovk commented on packages/client/src/components/organisms/form-change-password/form-change-password.logics.ts
> +    reset()
2 раза reset - это норм?

2023-04-10 14:44 UTC, ErikKhasanov approved these changes

2023-04-10 15:32 UTC, shoom1337-yt requested changes

2023-04-10 15:32 UTC, shoom1337-yt commented on packages/client/src/components/molecules/avatar/avatar.component.tsx
> +      if (target.files) formData.append('avatar', target.files[0])
ℹ️ Я бы здесь использовал блочную форму записи вместо однострочной. Если в будущем понадобится добавить какое-то ещё действие помимо `formData.append`, не будет лишнего шума в диффе.
Да и читается, на мой взгляд, лучше.

2023-04-10 15:32 UTC, shoom1337-yt commented on packages/client/src/components/organisms/form-profile/form-profile.component.tsx
> +        src={`https://ya-praktikum.tech/api/v2/resources/${user?.avatar}`}
❓Тут несколько комментариев:
- [ ] `user?.avatar` — если user или его avatar отсутствуют, то будет битая ссылка на картинку
- [ ] Урл до хранилища нужно вынести в константы, а ещё лучше — в константы брать из `.env`
- [ ] Как итог предыдущих комментов: вычисление `src` нужно вынести из разметки

2023-04-10 15:32 UTC, shoom1337-yt commented on packages/client/src/components/organisms/form-profile/form-profile.logics.ts
> +      phone: user?.phone || '',
ℹ️ Выглядит, как шаблонный код. При наличии времени, можно вынести генерацию этого объекта вынести в утилиту. Ключи `first_name, second_name etc` вынести в массив и пройтись циклом по нему.

2023-04-10 15:32 UTC, shoom1337-yt commented on packages/client/src/components/organisms/form-signin/form-signin.logics.ts
> +    const result = await dispatch(signIn(data))
❓ try/catch

2023-04-10 15:32 UTC, shoom1337-yt commented on packages/client/vite.config.ts.timestamp-1681137780556.mjs
❓ Наверное, нужно удалить?

2023-04-10 15:44 UTC, alheym approved these changes

2023-04-10 17:32 UTC, Lobanovk commented on packages/client/src/components/molecules/avatar/avatar.component.tsx
> +    const [avatarSrc, setAvatarSrc] = useState(avatarDefault)
тут надо useState(src || avatarDefault)

2023-04-10 17:32 UTC, Lobanovk commented on packages/client/src/components/molecules/avatar/avatar.component.tsx
> +    const [avatarSrc, setAvatarSrc] = useState(avatarDefault)
вот тут надо useState(src || avatarDefault)
и нижний useEffect удаляется

2023-04-10 17:32 UTC, Lobanovk commented on packages/client/src/components/organisms/form-profile/form-profile.logics.ts
> +  const [avatarSrc, setAvatarSrc] = useState('')
аналогично комментарию выше

2023-04-10 19:27 UTC, Lobanovk commented on packages/client/src/components/molecules/avatar/avatar.component.tsx
> +    const [avatarSrc, setAvatarSrc] = useState(src)
а зачем он здесь?

2023-04-11 11:44 UTC, shoom1337-yt approved these changes

2023-04-11 12:03 UTC, merged