Fix/auth
24-team-09/Arcade-2D-game pull request #41
Opened 2023-04-27 17:43 UTC by ErikKhasanov

### Какую задачу решаем
Закрываем роуты для неавторизованных пользователей

в routes/ сделал компонент ProtectedRoute, для оборачивания страниц в routes.tsx

Поправил index.tsx и App.tsx для того, чтоб можно было сделать инициализацию, а конкретнее getUser при первом рендере приложения.

Везде, где вызывался getUser в компонентах, его выпилил

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-27 17:55 UTC, Lobanovk requested changes

2023-04-27 17:55 UTC, Lobanovk commented on packages/client/src/components/molecules/avatar/avatar.component.tsx
> +      !src ? setAvatarSrc(avatarDefault) : setAvatarSrc(src)
вот это нельзя сразу в useState вынести? 
Просто при каждом изменение src он будет еще в стейт его класть, а это не есть хорошо

2023-04-27 17:55 UTC, Lobanovk commented on packages/client/src/components/organisms/form-signin/form-signin.logics.ts
> +        const queryParams = new URLSearchParams(window.location.search)
вот тут разве нельзя достать location из hook, который есть в react-router-dom
не совсем круто обращаться к window, если можем обойтись без него

2023-04-27 17:55 UTC, Lobanovk commented on packages/client/src/router/utils/ProtectedRoute.tsx
> +const ProtectedRoute: React.FC<Props> = ({ children }) => {
опять же, почему мы не можем обратится к hook из react-router?
https://reactrouter.com/en/main/hooks/use-location например?

2023-04-27 18:55 UTC, leopard-work approved these changes

2023-05-02 06:38 UTC, ErikKhasanov commented on packages/client/src/components/molecules/avatar/avatar.component.tsx
> +      !src ? setAvatarSrc(avatarDefault) : setAvatarSrc(src)
Поправил

2023-05-02 06:38 UTC, ErikKhasanov commented on packages/client/src/router/utils/ProtectedRoute.tsx
> +const ProtectedRoute: React.FC<Props> = ({ children }) => {
поправил

2023-05-02 06:38 UTC, ErikKhasanov commented on packages/client/src/components/organisms/form-signin/form-signin.logics.ts
> +        const queryParams = new URLSearchParams(window.location.search)
поправил

2023-05-02 16:47 UTC, merged