add oauth
24-team-09/Arcade-2D-game pull request #43
Opened 2023-05-01 19:25 UTC by oalbukova

### Какую задачу решаем

задача https://24-team-09.atlassian.net/browse/GAME-63

- добавлена OAuth-авторизация в проект

![image](https://user-images.githubusercontent.com/59943599/235514994-45a9749f-f83b-4fb8-8b7e-56189fb2ce41.png)

2023-05-02 16:52 UTC, leopard-work requested changes

2023-05-02 16:52 UTC, leopard-work commented on packages/client/src/components/layouts/header/header.styles.tsx
> +  marg
?

2023-05-02 18:08 UTC, leopard-work approved these changes

2023-05-02 20:38 UTC, Lobanovk commented on packages/client/src/components/organisms/form-signin/form-signin.test.tsx
> +
лишний пропуск

2023-05-02 20:38 UTC, Lobanovk commented on packages/client/src/components/templates/landing/landing.component.tsx
> +    const oauthCode = new URLSearchParams(window.location.search).get('code')
используй инструменты библиотеки react-router

2023-05-02 20:38 UTC, Lobanovk commented on packages/client/src/api/base.ts
> +export const RedirectUrl = 'http://localhost:3000'
вот этот параметр будет изменятся, если мы будем заливать куда-то?
если да, то стоит подумать, как передать его через переменные окружения

2023-05-07 16:54 UTC, oalbukova commented on packages/client/src/components/organisms/form-signin/form-signin.test.tsx
> +
убрала

2023-05-07 17:51 UTC, oalbukova commented on packages/client/src/components/templates/landing/landing.component.tsx
> +    const oauthCode = new URLSearchParams(window.location.search).get('code')
исправила

2023-05-07 21:22 UTC, oalbukova commented on packages/client/src/api/base.ts
> +export const RedirectUrl = 'http://localhost:3000'
добавила переменную окружения

2023-05-08 10:54 UTC, alheym approved these changes

2023-05-08 16:01 UTC, Lobanovk commented on packages/client/src/components/templates/landing/landing.component.tsx
> +      window.history.pushState({}, '', RedirectUrl)
вот это для чего?

2023-05-08 16:01 UTC, Lobanovk commented on packages/client/src/api/base.ts
> +export const RedirectUrl = process.env.VITE_OAUTH_REDIRECT_URL
где найти вот это значение?

2023-05-08 16:09 UTC, oalbukova commented on packages/client/src/api/base.ts
> +export const RedirectUrl = process.env.VITE_OAUTH_REDIRECT_URL
в файле .env

2023-05-08 16:28 UTC, Lobanovk commented on packages/client/src/api/base.ts
> +export const RedirectUrl = process.env.VITE_OAUTH_REDIRECT_URL
но в fail_changes нет .env) 
а прописать через команду запуска не получилось?)

2023-05-09 15:40 UTC, oalbukova commented on packages/client/src/components/templates/landing/landing.component.tsx
> +      window.history.pushState({}, '', RedirectUrl)
убрала, так как внесла изменения

2023-05-09 15:41 UTC, oalbukova commented on packages/client/src/api/base.ts
> +export const RedirectUrl = process.env.VITE_OAUTH_REDIRECT_URL
добавила в .env.sample

2023-05-09 15:52 UTC, Lobanovk approved these changes

2023-05-10 06:04 UTC, ErikKhasanov approved these changes

2023-05-11 06:46 UTC, shoom1337-yt requested changes

2023-05-11 06:46 UTC, shoom1337-yt commented on packages/client/src/components/organisms/form-signin/form-signin.logics.ts
> +  const handleOauth = (): void => {
ℹ️ Тут типизация возвращаемого значения — оверхед. Можно смело убрать `: void` и TS выведет тип.
Попробуй в редакторе:
<img width="334" alt="image" src="https://github.com/24-team-09/Arcade-2D-game/assets/128394879/47ee307d-a0eb-40a3-b97d-f985b56514be">

2023-05-11 06:46 UTC, shoom1337-yt commented on packages/client/src/components/organisms/form-signin/form-signin.logics.ts
> +  const handleOauth = (): void => {
❓ А вот в useCallback хэндлер обернуть нужно. 
(Как и другие методы, возвращаемые из хуков. Упустил на прошлых ревью.)
В таких небольших приложениях, такая оптимизация, не очень заметна. Но на реальных проектах стоит использовать везде, чтобы не переделывать потом)

2023-05-11 09:41 UTC, shoom1337-yt approved these changes

2023-05-11 09:42 UTC, merged