Feat/game 64
24-team-09/Arcade-2D-game pull request #45
Opened 2023-05-04 05:39 UTC by alheym

### Какую задачу решаем
Задача: https://24-team-09.atlassian.net/browse/GAME-64

Добавить API для лидерборда

### Скриншоты/видяшка (если есть)

![image](https://user-images.githubusercontent.com/42946614/236120344-f12f3927-6fc3-4dcd-b7fd-e46d22210b9e.png)

2023-05-04 09:25 UTC, leopard-work commented on packages/client/src/router/routes.tsx
> +          </ProtectedRoute>),
Без авторизации не работает?
Записи в конце игры сейчас нету?

2023-05-04 09:33 UTC, alheym commented on packages/client/src/router/routes.tsx
> +          </ProtectedRoute>),
насколько поняла, то api работает только при авторизованном пользователе

2023-05-06 15:22 UTC, Lobanovk requested changes

2023-05-06 15:22 UTC, Lobanovk commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +    const s = data.filter(el => el.name.indexOf(search) !== -1)
что такое s

2023-05-06 15:22 UTC, Lobanovk commented on packages/client/src/components/organisms/game/end-view/end-view.component.tsx
> +      avatar: user?.avatar,
зачем здесь avatar?

2023-05-06 15:22 UTC, Lobanovk commented on packages/client/src/components/organisms/game/end-view/end-view.component.tsx
> +      avatar: user?.avatar,
и почему напрямую, без обертки в редакс? 
Может же быть ошибка, которую надо будет отобразить

2023-05-06 15:22 UTC, Lobanovk commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +  const sortedData = sortData.map((el, index) => ({ ...el, position: index + 1 }))
position высчитывать от index, кажется не совсем классная идея)

2023-05-06 15:22 UTC, Lobanovk commented on packages/client/src/components/templates/statistics/statistics.component.tsx
> +    getLeaderboardList(10).then(response => {
вот это бы затащить в redux 
и сделать так, что мы могли бы запрашивать 10 только при первом рендере

2023-05-10 08:10 UTC, alheym commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +    const s = data.filter(el => el.name.indexOf(search) !== -1)
поправила имя переменной

2023-05-10 08:10 UTC, alheym commented on packages/client/src/components/organisms/game/end-view/end-view.component.tsx
> +      avatar: user?.avatar,
добавила обертку

2023-05-10 08:11 UTC, alheym commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +  const sortedData = sortData.map((el, index) => ({ ...el, position: index + 1 }))
исправила

2023-05-10 12:42 UTC, Lobanovk requested changes

2023-05-10 12:42 UTC, Lobanovk commented on packages/client/src/components/organisms/game/end-view/end-view.component.tsx
> +    const addLeader = async () => {
вот тут это не надо
просто dispatch(addLeaderboardItem({
            score: score,
            name: user?.login,
            avatar: user?.avatar,
          }))
          
          ты ошибку в самом action обработала

2023-05-10 12:42 UTC, Lobanovk commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +    const position = sortData.indexOf(el) + 1
ну вообще я говорил что высчитывать position исходя из индекса не правильно)
за что отвечает position? за номер в строчке лидеров
например ["дмитрий", "антон", "иван"]
Тут получается первый Дмитрий

а теперь фильтруем по имени -> ["антон", "дмитрий", "иван"] и вот первый у нас Антон) 
Хотя это не так)

2023-05-11 09:33 UTC, alheym commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +    const position = sortData.indexOf(el) + 1
если правильно тебя поняла, то исправила
![image](https://github.com/24-team-09/Arcade-2D-game/assets/42946614/a9fcf53c-59c7-4686-b4e5-150ecfe210a8)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/42946614/f44ba761-30bb-4c86-91f3-7502e3c5994d)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/42946614/86deec3f-a9dc-4a99-b35d-4cdf152cb2ca)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/42946614/fd3fb8fb-18b1-4a9a-8c65-89fdecf65a6f)

2023-05-11 16:03 UTC, Lobanovk approved these changes

2023-05-12 05:42 UTC, ErikKhasanov approved these changes

2023-05-12 08:11 UTC, shoom1337-yt requested changes

2023-05-12 08:11 UTC, shoom1337-yt commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +            <img src={avatar ? avatar : avatarDefault} alt={name} />
❓ Вычисление аватарки давай вынесем из разметки. Можно сразу при деструктуризации из пропса задать дефолтное значение.

2023-05-12 08:11 UTC, shoom1337-yt commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +    let filteredData = data
❓ Копируем ссылку на входящий массив данных. Чтобы избежать его мутации, и неожиданных эффектов в других местах, давай скопируем спредом?

2023-05-12 08:11 UTC, shoom1337-yt commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +
ℹ️ Все эти методы я бы вынес в отдельный хук. Так логика и отображение будут разделены и компонент станет проще поддерживать в будущем.

2023-05-12 08:50 UTC, alheym commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +            <img src={avatar ? avatar : avatarDefault} alt={name} />
сделала

2023-05-12 08:50 UTC, alheym commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +    let filteredData = data
сделала

2023-05-12 08:50 UTC, alheym commented on packages/client/src/components/organisms/leaderboard/leaderboard.component.tsx
> +
сделала

2023-05-12 10:14 UTC, shoom1337-yt approved these changes

2023-05-15 16:19 UTC, merged