Feat/game 65 Добавить ещё одно WEB API (кроме Canvas, Fetch)
24-team-09/Arcade-2D-game pull request #47
Opened 2023-05-04 17:51 UTC by leopard-work

### [GAME-65 Добавить ещё одно WEB API (кроме Canvas, Fetch)](https://24-team-09.atlassian.net/browse/GAME-65?atlOrigin=eyJpIjoiZWE1ZjUzMmEzMWVjNGZiNDkxMmMzNDIwMjg1ZDBhM2IiLCJwIjoiaiJ9)

Добавлен fullscreen в игре

### Демонстрация

https://user-images.githubusercontent.com/83064000/236287516-44085735-b0f9-4331-9687-39f9a197ea47.mp4

2023-05-05 10:02 UTC, alheym approved these changes

2023-05-06 15:13 UTC, Lobanovk requested changes

2023-05-06 15:13 UTC, Lobanovk commented on packages/client/src/components/organisms/game/game.component.tsx
> +    if (isGameFullScreen) document.documentElement.requestFullscreen().then()
оберни в {} для читабельности

2023-05-06 15:13 UTC, Lobanovk commented on packages/client/src/components/organisms/game/game.component.tsx
> +    addEventListener('fullscreenchange', event => {
а где удаление этого слушателя?

2023-05-06 16:31 UTC, leopard-work commented on packages/client/src/components/organisms/game/game.component.tsx
> +    addEventListener('fullscreenchange', event => {
Совсем забыл...

2023-05-10 06:04 UTC, ErikKhasanov approved these changes

2023-05-11 18:37 UTC, merged