Feat/game 66 Инициализация store на ssr
24-team-09/Arcade-2D-game pull request #50
Opened 2023-05-13 13:57 UTC by ErikKhasanov

### Какую задачу решаем
https://24-team-09.atlassian.net/browse/GAME-66
Создал сервис для получения запроса данных юзера в server/repository/apiRepository и на клиенте в api и services
Прокидываю значения redux из ssr на клиент в client/src/index.ts
### Скриншоты/видяшка (если есть)
![изображение](https://github.com/24-team-09/Arcade-2D-game/assets/58214379/4030a056-2ccd-4a13-b8f8-689bfbc6cb41)
### TBD (если есть)

2023-05-14 15:24 UTC, Lobanovk commented on packages/client/src/store/store.ts
> +  console.log('store', store.getState())
console.log

2023-05-14 15:24 UTC, Lobanovk commented on packages/client/src/store/store.ts
> +  getUser(): Promise<User>
я бы сделал его объектом, с ключами отвечающими за определенные сервисы
это если посмотреть в будущее, то у нас на странице форума, мы должны запросить информацию по нему. И сделать это можно с node, просто прокинув нужный сервис

2023-05-14 15:24 UTC, Lobanovk commented on packages/client/ssr.tsx
> +  // if (path === Path.DEFAULT) {
для чего эти комменты?

2023-05-14 15:24 UTC, Lobanovk commented on packages/server/index.ts
> +        console.log('cookies', req.headers?.cookie)
console.log

2023-05-14 15:24 UTC, Lobanovk commented on packages/client/ssr.tsx
> +const getDataForRoute = async (path: string, dispatch: AppDispatch) => {
и почему бы не запихнуть это в loader? 
https://youtu.be/G-HHcOwNjZs?t=1325

вот тут прям показано, как можно прокинуть dispatch в сам loader

2023-05-14 20:29 UTC, leopard-work approved these changes

2023-05-15 06:04 UTC, shoom1337-yt requested changes

2023-05-15 06:04 UTC, shoom1337-yt commented on packages/client/src/store/store.ts
> +  getUser(): Promise<User>
Поддерживаю Кирилла

2023-05-15 06:04 UTC, shoom1337-yt commented on packages/client/src/components/organisms/form-change-password/form-change-password.logics.ts
> +        if (result.meta.requestStatus === 'fulfilled') {
❓ Непривычная конструкция. Подскажи, почему пришлось проверять статус промиса?

2023-05-15 07:09 UTC, ErikKhasanov commented on packages/client/ssr.tsx
> +  // if (path === Path.DEFAULT) {
Это пример как использовать лоадер по урлу, для других страниц

2023-05-15 10:50 UTC, ErikKhasanov commented on packages/client/src/store/store.ts
> +  console.log('store', store.getState())
удалил

2023-05-15 11:44 UTC, ErikKhasanov commented on packages/client/src/store/store.ts
> +  getUser(): Promise<User>
Сделал для user

2023-05-15 11:46 UTC, ErikKhasanov commented on packages/client/ssr.tsx
> +const getDataForRoute = async (path: string, dispatch: AppDispatch) => {
на v6 так не работает, из-за новых типов в loader можно прокидывать только request, params, context, причем все они обязательные. Другое решение с createRoutes(...) создает слишком много кода. Пока можно использовать эту функцию как основную. с появлением новых урлов, можно спросить у наставника, как лучше это сделать

2023-05-15 11:46 UTC, ErikKhasanov commented on packages/client/src/components/organisms/form-change-password/form-change-password.logics.ts
> +        if (result.meta.requestStatus === 'fulfilled') {
не мой код, просто форматтер прошелся, это было в апи уже.

2023-05-16 08:05 UTC, shoom1337-yt approved these changes

2023-05-22 18:59 UTC, merged