Feat/game 71 Реализовать API форума
24-team-09/Arcade-2D-game pull request #52
Opened 2023-05-19 15:25 UTC by leopard-work

### [GAME-71 Реализовать API форума](https://24-team-09.atlassian.net/browse/GAME-71?atlOrigin=eyJpIjoiNGYzZTYzYTBhZmIyNGY4MmFlZDk5N2FiNWI2ZTQ4M2MiLCJwIjoiaiJ9)

**Для ревьера:** задача из беклога до изменения т.е. только сервер, клиент будет доработан в другой задаче

**Запуск:**
- удалить папку tmp/pgdata
- запустить базу из консоли docker-compose up -d postgres
- yarn dev (если не работает собрать ssr yarn build:ssr)

**Реализованы модели для форума:**
- категории (id title description)
- темы (title parent_id user_id), связи с категорией и пользователем
- сообщения (message parent_id user_id), связи с темой и пользователем
- пользователи (user_id login avatar)

**Контроллеры:**
- Получение категорий вместе с количеством тем и последней темой + привязанным пользователем в этой категории (http://localhost:3001/api/forum)
- Получение тем с количеством постов и привязанным пользователем (http://localhost:3001/api/forum/topic/:id)
- Получение сообщений с привязанным пользователем (http://localhost:3001/api/forum/post/:id)
- Добавление темы (http://localhost:3001/api/forum/topic)
- Добавление сообщения (http://localhost:3001/api/forum/post)

![image](https://github.com/24-team-09/Arcade-2D-game/assets/83064000/f9fd9615-530f-4de8-bf3e-a794a33f745f)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/83064000/d079d884-04b2-4ff6-b06f-6bc66d826470)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/83064000/a1863603-3d68-4726-b387-6cb6b132f999)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/83064000/10cdbf41-887c-4af8-8c7b-4b038ce064e1)

### Демонстрация работы:
https://github.com/24-team-09/Arcade-2D-game/assets/83064000/f333c38f-bf50-4dc4-ad8a-a49bf7345390

2023-05-22 11:04 UTC, Lobanovk commented on packages/client/src/components/organisms/forum/forum-logic.ts
> +        // TODO изменить в следующей задаче
в какой задаче, кинь сылочку хотя бы

2023-05-22 11:04 UTC, Lobanovk commented on packages/client/src/components/organisms/forum/forum-logic.ts
> +        let url = 'http://localhost:3001/api/forum/addTopic/'
 и почему это не action?
Почему данные не добавляются в локальный стор приложения?

2023-05-22 11:18 UTC, leopard-work commented on packages/client/src/components/organisms/forum/forum-logic.ts
> +        // TODO изменить в следующей задаче
Может некорректно описал, текущая на 2 была поделена, все что связано с клиентом идет туда
https://24-team-09.atlassian.net/browse/GAME-80?atlOrigin=eyJpIjoiNjllNDE5OWUyYzFkNGMyOGIyMmIxNjRkMDYyZmQ0MDIiLCJwIjoiaiJ9

2023-05-22 11:29 UTC, leopard-work commented on packages/client/src/components/organisms/forum/forum-logic.ts
> +        // TODO изменить в следующей задаче
Комментарии ниже я учел, будут реализованы там

2023-05-22 11:38 UTC, leopard-work commented on migrations/dbinit.sql
> +    user_id INTEGER,
Добавил в модели, а тут забыл...
Поправлено

2023-05-22 11:38 UTC, leopard-work commented on migrations/dbinit.sql
> +    id SERIAL,
++

2023-05-22 11:48 UTC, Lobanovk approved these changes

2023-05-22 18:55 UTC, shoom1337-yt requested changes

2023-05-22 18:55 UTC, shoom1337-yt commented on packages/client/src/components/organisms/forum/forum-logic.ts
> +        }
ℹ️ Получается практически копипаст с двумя строками выше. Попробуй отрефакторить, чтобы не приходилось дублировать логику и переопределять переменные data и url.

2023-05-22 18:55 UTC, shoom1337-yt commented on packages/client/src/components/organisms/forum/forum-types.ts
> +  user: unknown
В каком случае юзер не определён? Вроде, для форума нужна авторизация, инфа пользователя должна быть...

2023-05-22 18:55 UTC, shoom1337-yt commented on packages/server/db.ts
> +    await sequelize.sync()
❓ sync используется, тогда и таблички должны из моделей подтягиваться, без описания на SQL в dbinit?

2023-05-22 18:55 UTC, shoom1337-yt commented on packages/server/src/models/forumPosts.ts
> +    onUpdate: 'CASCADE',
🚀 Отлично, что про каскадность не забыл)

2023-05-22 18:55 UTC, shoom1337-yt commented on packages/server/src/routes/forum.ts
> +forumRouter.post('/addTopic/', forumController().addForumTopic)
ℹ️ По REST должно быть так:
GET /topic — для получения всех топиков
POST /topic — для создания нового

Так же и с постами. Получается нагляднее и проще.

2023-05-23 06:52 UTC, leopard-work commented on packages/server/db.ts
> +    await sequelize.sync()
убрал

2023-05-23 06:53 UTC, leopard-work commented on packages/server/src/routes/forum.ts
> +forumRouter.post('/addTopic/', forumController().addForumTopic)
спасибо, поменял

2023-05-23 06:55 UTC, leopard-work commented on packages/client/src/components/organisms/forum/forum-logic.ts
> +        }
да, это и следующий комментарий будет редактироваться, просто не в этой ветке

2023-05-23 06:57 UTC, leopard-work commented on packages/server/src/controllers/forum.ts
> +                '(select count(topics.id) from topics where "topics"."parent_id" = "categories"."id")'
Мне кажется быстрее будет рассчитывать это на сервере, чем передавать на страницу категорий еще и все темы и считать)

2023-05-23 07:40 UTC, shoom1337-yt commented on packages/server/src/controllers/forum.ts
> +                '(select count(topics.id) from topics where "topics"."parent_id" = "categories"."id")'
Зато возрастает нагрузка на БД и может родиться холивар с нагрузчиками))

Последний вопрос: раньше не сталкивался с literal, не знаешь, оно как-то оптимизируется под капотом? Всмысле, "сложится" это с основным запросом или всё же будет дополнительный?

Так просто, для общего развития)

2023-05-23 07:53 UTC, leopard-work commented on packages/server/src/controllers/forum.ts
> +                '(select count(topics.id) from topics where "topics"."parent_id" = "categories"."id")'
literal делает запрос в рамках sequelize модели, т.е. складывается с основным, в консоли сам sql запрос можно увидеть при срабатывании

2023-05-23 10:57 UTC, shoom1337-yt approved these changes

2023-05-23 10:59 UTC, shoom1337-yt approved these changes

2023-05-23 18:17 UTC, ErikKhasanov approved these changes

2023-05-23 18:34 UTC, merged