add forum api
24-team-09/Arcade-2D-game pull request #57
Opened 2023-05-27 08:12 UTC by ErikKhasanov

### Какую задачу решаем
https://24-team-09.atlassian.net/browse/GAME-79
Поддержать API форума на клиенте
Сделал store для форума, лоадер и добавление постов, топиков
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-28 07:24 UTC, shoom1337-yt requested changes

2023-05-28 07:24 UTC, shoom1337-yt commented on lerna-debug.log
❓ Лог нужно удалить и добавить в gitignore.

2023-05-28 07:24 UTC, shoom1337-yt commented on packages/client/src/api/authService.ts
> +      // TODO убрать NODE_API_URL
❓ Поддерживаю. Вопрос только: каким образом планируется убрать?

2023-05-28 07:24 UTC, shoom1337-yt commented on packages/client/src/components/molecules/loader/loader.styles.tsx
> +  border: 10px solid #f3f3f3;
❓ Убери, пожалуйста, цвет в CSS-переменную.

2023-05-28 07:24 UTC, shoom1337-yt commented on packages/client/src/store/forum/actions.ts
> +const BACKEND_URL = 'http://localhost:3001/api/forum'
❓`http://localhost:3001` — переменная окружения и не относится к коду клиентского приложения, адрес и порт, теоретически, могут поменяться со временем. Поэтому, значение нужно вынести в `.env`. В таком случае, при изменения адреса бэка, не нужно будет пересобирать клиентское приложение.

2023-05-28 07:24 UTC, shoom1337-yt commented on packages/client/vite.config.ts.timestamp-1685116801025.mjs
❓ Этот файл тоже не должен попадать в репозиторий. Сбилдился не туда?

2023-05-28 07:24 UTC, shoom1337-yt commented on packages/server/src/controllers/forum.ts
> +          if (e.message === 'Ресурс не найден') {
ℹ️ Если `e` — ошибка аксиоса, то можно использовать тип AxiosError. По-моему, он описывает и `message`, тогда получится убрать один уровень вложенности.

2023-05-28 07:49 UTC, ErikKhasanov commented on packages/client/src/api/authService.ts
> +      // TODO убрать NODE_API_URL
Т.к у нас 2 api, один прокси на /api/v2 - практикум, второй /api - нашего бека, в файле baseApi прописывать не просто path, а писать полностью с api -которое мы используем, тогда не нужно будет в каких-то actions использовать другой BaseUrl, вроде как-то так, на неделе доработок надо заняться этим ) Может ребята что предложат

2023-05-28 07:51 UTC, ErikKhasanov commented on packages/client/src/components/molecules/loader/loader.styles.tsx
> +  border: 10px solid #f3f3f3;
убрал

2023-05-28 07:55 UTC, ErikKhasanov commented on packages/client/src/store/forum/actions.ts
> +const BACKEND_URL = 'http://localhost:3001/api/forum'
Проблема сейчас в том, что в api/ где создается экземпляр axios прописывается baseUrll = 'https://ya-praktikum.tech/api/v2/', поэтому тут тоже, как выше надо всё переделать)

2023-05-28 07:56 UTC, ErikKhasanov commented on packages/client/vite.config.ts.timestamp-1685116801025.mjs
я не понял, откуда эти timestamp начали попадать, раньше их не было, удалил

2023-05-28 07:56 UTC, ErikKhasanov commented on packages/server/src/controllers/forum.ts
> +          if (e.message === 'Ресурс не найден') {
e - это ручная ошибка получается, если пустой массив, отдать 404 код ошибки

2023-05-28 08:03 UTC, shoom1337-yt approved these changes

2023-05-28 08:03 UTC, shoom1337-yt approved these changes

2023-05-29 06:24 UTC, leopard-work approved these changes

2023-05-29 07:05 UTC, merged