Feat/game 77
24-team-09/Arcade-2D-game pull request #58
Opened 2023-05-27 12:44 UTC by oalbukova

### Какую задачу решаем
Задача: https://24-team-09.atlassian.net/browse/GAME-77

Переключение темы (бек)

### Скриншоты/видяшка (если есть)
результат запроса:
![image](https://github.com/24-team-09/Arcade-2D-game/assets/59943599/f0a8582b-ffb9-4049-a51a-a9a4f48ce12b)
![image](https://github.com/24-team-09/Arcade-2D-game/assets/59943599/293c2c4c-1267-4b7d-862f-7d7eb474e487)

таблицы:
![image](https://github.com/24-team-09/Arcade-2D-game/assets/59943599/2441d042-a972-4d24-9a9f-c75fdad76448)

2023-05-27 12:50 UTC, alheym approved these changes

2023-05-27 13:06 UTC, ErikKhasanov commented on packages/client/vite.config.ts.timestamp-1685118227228.mjs
лишний файл

2023-05-27 13:09 UTC, oalbukova commented on packages/client/vite.config.ts.timestamp-1685118227228.mjs
удалила

2023-05-28 07:32 UTC, shoom1337-yt requested changes

2023-05-28 07:32 UTC, shoom1337-yt commented on packages/server/src/models/forumEmoji.ts
❓ Задача про темизацию. Как сюда попали ещё и эмоджи?

2023-05-28 07:32 UTC, shoom1337-yt commented on packages/server/src/controllers/themes.ts
> +        return res.status(404).json('для пользователя нет темы')
ℹ️ Для красоты, можно текст сообщения пользователю вынести в константы.

2023-05-28 07:32 UTC, shoom1337-yt commented on packages/server/src/routes/themes.ts
> +themeRouter.post('/userTheme', themeController().addUserTheme)
ℹ️ Не обязательно, но я бы переименовал роут в `/user-theme`. Заглавные буквы хоть и работают, но по разным соглашениям не используются.
А лучше, вообще `/theme`  🙂

2023-05-28 11:04 UTC, shoom1337-yt approved these changes

2023-05-28 11:07 UTC, closed without merging